# Generated by Django 5.0.6 on 2024-06-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='Description',
            new_name='description',
        ),
    ]
